Copy Excercise react
zigelbaum/reactTraining pull request #1
Opened 2023-12-24 22:10 UTC by zigelbaum

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/CartItem.tsx
> +        <>
remove unused <></> tags

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/CartTab.tsx
> +  const [orderSuccessOpen, setOrderSuccessOpen] = useState(false);
```suggestion
  const [orderSuccessOpen, setOrderSuccessOpen] = useState<boolean>(false);
```
also for the rest of the code

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/ProductsListTab.tsx
> +import InfoIcon from '@mui/icons-material/Info';
you can import both from @mui/icons-material

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/OrderCompleteDialog.tsx
> +const OrderCompleteDialog: React.FC<OrderCompleteProps> = ({open, onCloseClick}) => {
```suggestion
const OrderCompleteDialog = (props: OrderCompleteProps) => {
```
in globus we use a different syntax for this

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/CartTab.tsx
> +          <Snackbar
this `<Snackbar/>` is used twice and is valuable on its own, It should be a seperate component

2023-12-25 09:13 UTC, AsafL910 commented on package.json
In globus we use `vite` instead of `create react app`. Try to switch the project to it so you are familiar with it.

2023-12-25 09:13 UTC, AsafL910 commented on src/App.tsx
> +      <AppBar position='sticky'>
`AppBar` should be a seperate component

2023-12-25 09:13 UTC, AsafL910 commented on src/App.tsx
> +      <Box sx={{ display: 'flex', justifyContent: 'flex-end' }}>
this can be implemented with the `<TabList/>` mui component

2023-12-25 09:13 UTC, AsafL910 commented on src/data/products.json
for your conponents to be testable with QA automation, I want you to add a `testid` prop for each component. I'll show it to you later.

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/ProductsListTab.tsx
> +  const [selectedProduct, setSelectedProduct] = useState<Product | undefined>(undefined);
I would like you to export some of these states and the loading of the cart items from a custom hook.

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/ProductsListTab.tsx
> +              <Card sx={{ width: 300, height: 345, display: 'flex', flexDirection: 'column' }}>
each `<Card/>` should be its own component

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/ProductInfo.tsx
> +                <CardMedia
this should probably not be `CardMedia` since it is not inside a `Card` component

2023-12-25 09:13 UTC, AsafL910 commented on src/comps/CartTab.tsx
> +              <LinearProgress variant="determinate" value={progress} sx={{ width: '200px' }} />
ProgressBar has some states and logic here so it should be a seperate component

2024-01-15 17:04 UTC, AsafL910 requested changes

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/AlertSnackBar.tsx
> +    alertSeverity: AlertColor | undefined;
why should the severity be undefined?

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/CartTab.tsx
> +  const dispatch = useDispatch();
lately in globus we started to implement custom hooks in the project. Try to bundle some of the logic here into a custom hook and export it to use here.

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/CartTab.tsx
> +          <List>
If you put it all inside a `List` anyway then it can be a seperate component maybe

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/OrderCompleteDialog.tsx
> +import React from 'react'
we usually don't need to import all of `React` since we use specific functions every time.
Relevant for the entire project

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/ProductCard.tsx
> +    p: Product;
`p` is not a clear name

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/ProductCard.tsx
> +                <Typography variant="h6" color="text.secondary" sx={{ textAlign: 'center' }}>
```suggestion
                <Typography variant="h6" color="secondary" sx={{ textAlign: 'center' }}>
```

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/ProductInfo.tsx
> +    product?: Product;
why is product optional?

2024-01-15 17:04 UTC, AsafL910 commented on src/comps/ProductsListTab.tsx
> +  const [selectedProduct, setSelectedProduct] = useState<Product | undefined>(undefined);
Why is this state needed? (selectedProduct)

2024-01-15 17:04 UTC, AsafL910 commented on package.json
Make sure you prepare answers for the questions in the `README`

2024-01-16 08:26 UTC, zigelbaum commented on src/comps/ProductCard.tsx
> +                <Typography variant="h6" color="text.secondary" sx={{ textAlign: 'center' }}>
text.secondary is the name of the color (light gray). secondary by itself is purple
![color](https://github.com/zigelbaum/reactTraining/assets/57626914/c7f03bc4-226a-4f3b-9967-7772ce3ac011)

2024-01-16 08:27 UTC, zigelbaum commented on src/comps/ProductsListTab.tsx
> +  const [selectedProduct, setSelectedProduct] = useState<Product | undefined>(undefined);
for sending it as props to productInfo component

2024-01-18 08:29 UTC, AsafL910 requested changes

2024-01-18 08:29 UTC, AsafL910 commented on src/hooks/useOrder.ts
> +    useEffect(() => {
why is this useEffect needed?

2024-01-28 17:30 UTC, closed without merging